# Generated by Django 5.0.6 on 2024-05-18 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=128, null=True)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("phone_number", models.CharField(max_length=32)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="users")),
                ("cr_on", models.DateTimeField(auto_now_add=True)),
                ("up_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Merchants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_name", models.CharField(max_length=128)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="Merchants"),
                ),
                ("address", models.CharField(max_length=1024)),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("cr_on", models.DateTimeField(auto_now_add=True)),
                ("up_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cr_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_created_by",
                        to="users.users",
                    ),
                ),
                (
                    "up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_updated_by",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
            },
        ),
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership",
                    models.CharField(
                        choices=[
                            ("M", "Manager"),
                            ("T", "Top_manager"),
                            ("D", "Director"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("cr_on", models.DateTimeField(auto_now_add=True)),
                ("up_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cr_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_created_by",
                        to="users.users",
                    ),
                ),
                (
                    "up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_updated_by",
                        to="users.users",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="User",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
            },
        ),
    ]
