# Generated by Django 5.0.6 on 2024-05-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="email",
        ),
        migrations.AlterField(
            model_name="users",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
