# Generated by Django 5.0.6 on 2024-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baskets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basket_id", models.CharField(max_length=256)),
                ("added_time", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_basket",
                        to="users.users",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_in_basket",
                        to="products.books",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basket",
                "verbose_name_plural": "Baskets",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (1, "Open"),
                            (2, "Execution of payment"),
                            (3, "Error"),
                            (4, "Success"),
                            (5, "Canceled"),
                            (6, "Blocked"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("cipher", models.CharField(max_length=1024)),
                ("amount", models.PositiveIntegerField()),
                ("order_details", models.TextField()),
                ("cr_on", models.DateTimeField(auto_now_add=True)),
                ("basket", models.ManyToManyField(to="orders.baskets")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
