# Generated by Django 5.0.6 on 2024-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=128)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("last_name", models.CharField(max_length=128)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="Books/Authors"),
                ),
                ("biography", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("cr_on", models.DateTimeField(auto_now_add=True)),
                (
                    "cr_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="added_by",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128)),
                ("book_publisher", models.CharField(max_length=128)),
                ("year_of_publishing", models.DateField(blank=True, null=True)),
                ("count_of_page", models.PositiveIntegerField()),
                ("book_size", models.CharField(max_length=64)),
                ("cover_type", models.CharField(max_length=64)),
                ("book_weight", models.PositiveIntegerField()),
                ("age_limit", models.CharField(max_length=16)),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="books"),
                ),
                ("price", models.PositiveIntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("added_time", models.DateTimeField(auto_now_add=True)),
                ("authors", models.ManyToManyField(to="products.authors")),
                ("library", models.ManyToManyField(to="users.merchants")),
                ("genre", models.ManyToManyField(to="products.genre")),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
