# Generated by Django 5.0.6 on 2024-05-18 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_genre_cr_by_languages_books_languages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
    ]
